# Generated by Django 2.2.7 on 2020-01-27 19:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_user_lastseen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_lastseen',
            name='last_seen',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 27, 21, 54, 43, 411954)),
        ),
    ]
