# Generated by Django 3.0.2 on 2020-02-09 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20200209_0855'),
        ('account', '0004_auto_20200206_0822'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='orders',
            field=models.ManyToManyField(related_name='profile_orders', to='products.products'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.IntegerField(blank=True, max_length=12, null=True),
        ),
    ]
