# Generated by Django 3.0.2 on 2020-02-09 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20200209_0855'),
        ('account', '0006_auto_20200209_1028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='orders',
            field=models.ManyToManyField(blank=True, related_name='profile_orders', to='products.products'),
        ),
    ]
