# Generated by Django 3.0.2 on 2020-02-09 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_cart_item_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='total',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cart_item',
            name='total',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
