# Generated by Django 3.0.2 on 2020-02-10 09:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cart', '0003_auto_20200209_0948'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items', models.ManyToManyField(related_name='items_orders', to='cart.cart_item')),
                ('user_ordered', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='all_orders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
