# Generated by Django 3.0.2 on 2020-02-03 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('descreption', models.TextField()),
                ('price', models.PositiveIntegerField()),
                ('image', models.ImageField(height_field=200, upload_to='images/', width_field=200)),
                ('category', models.CharField(choices=[('electronics', 'GREEN'), ('home', 'BLUE'), ('beauty & health', 'RED'), ('fashion', 'ORANGE'), ('our market', 'BLACK'), ('daily deals', 'BLACK')], default='home', max_length=30)),
                ('isNew', models.BooleanField(default='False')),
                ('isBestSeller', models.BooleanField(default='False')),
            ],
        ),
    ]
