# Generated by Django 3.0.2 on 2020-02-03 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='category',
            field=models.CharField(choices=[('electronics', 'ELECTRONICS'), ('home', 'HOME'), ('beauty & health', 'BEAUTY & HEALTH'), ('fashion', 'FASHION'), ('our market', 'OUR MARKET'), ('daily deals', 'DAILY DEALS'), ('mobiles', 'MOBILES'), ('baby', 'BABY')], default='home', max_length=30),
        ),
    ]
