# Generated by Django 3.0.2 on 2020-02-03 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_products_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.ImageField(default='static/images/The_Fresh_Market_logo.svg', height_field=100, upload_to='images/', width_field=100),
        ),
    ]
