# Generated by Django 3.0.2 on 2020-02-03 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20200203_1729'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='category',
            field=models.CharField(choices=[('new', 'NEW'), ('electronics', 'ELECTRONICS'), ('mobiles', 'MOBILES'), ('home', 'HOME'), ('beauty & health', 'BEAUTY & HEALTH'), ('baby', 'BABY'), ('fashion', 'FASHION'), ('our market', 'OUR MARKET'), ('hot deals', 'HOT DEALS')], default='NEW', max_length=50),
        ),
    ]
