# Generated by Django 3.0.2 on 2020-02-09 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_products_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='category',
            field=models.CharField(blank=True, choices=[('new', 'NEW'), ('electronics', 'ELECTRONICS'), ('mobiles', 'MOBILES'), ('home', 'HOME'), ('beauty & health', 'BEAUTY & HEALTH'), ('baby', 'BABY'), ('fashion', 'FASHION'), ('our market', 'OUR MARKET'), ('hot deals', 'HOT DEALS')], default='NEW', max_length=50, null=True),
        ),
    ]
